Fix TypeError: unsupported operand type(s) for -: 'str' and 'int' in activateMiracle.py
Sometimes the enddate is a string. This fixes this for all cases where enddate and current date both only contain numbers or decimal points.

Error I want to fix with this:
```
Error in:

I activate the miracle Hephaestus’ Forge 7777777777777 times

Cause:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/ikabot/function/activateMiracle.py", line 304, in activateMiracle
    do_it(session, island, iterations)
  File "/usr/lib/python3.12/site-packages/ikabot/function/activateMiracle.py", line 371, in do_it
    wait_for_miracle(session, island)
  File "/usr/lib/python3.12/site-packages/ikabot/function/activateMiracle.py", line 337, in wait_for_miracle
    wait_time = enddate - currentdate
                ~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```